theme: jekyll-theme-slate

title                    : "PANDA"
title_separator          : "-"
name                     : &name "Your Name"
description              : &description "personal description"
url                      : https://github.com/panda-planner-dev
repository               : "panda-planner-dev"
